language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install polymer-cli
  - export PATH=$PWD/node_modules/.bin:$PATH
  - polymer install --variants
script:
  - xvfb-run polymer test
